### ISSUE TITLE
Reduce space between Phippy and friends on mobile

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#244]
Is there an easy way to reduce the space between Phippy and his friends as they're [listed here](https://dev-cncfci.pantheonsite.io/phippy/) on mobile?
<img width="357" alt="Screen Shot 2020-08-17 at 1 00 15 PM" src="https://user-images.githubusercontent.com/463160/90358823-b3ce3b00-e089-11ea-8231-b7d8db3dcd43.png">

**Comment by thetwopct** [comment]
The columns use flex box, so the height of each row/column is set by the larges item, which means Phippy with his long neck is twice the size of everything else. I'll see if we can make a column style that will get rid of this for this situation.

**Comment by thetwopct** [comment]
I've added a no flex on mobile style for columns, which should solve it. But I've realised that his Friends all have padding above them, so that extra space isn't from CSS, its inside the SVG. When you uploaded them, perhaps Autocrop was turned off?

![20200818183923-Web Inspector — dev-cncfci pantheonsite io — phippy](https://user-images.githubusercontent.com/10615884/90546659-481bc900-e182-11ea-862f-bcbfea3af7d9.jpg)

**Comment by cjyabraham** [comment]
I tried autocropping Goldie but now on desktop it looks like out of proportion:
<img width="1273" alt="Screen Shot 2020-08-19 at 11 47 30 AM" src="https://user-images.githubusercontent.com/463160/90589948-e7d46800-e211-11ea-846d-8fa944f6d6d4.png">

I set it back to how it was... Maybe we should just set this as a nice-to-have for now?

**Comment by thetwopct** [comment]
Alternative would be to add a style that would have 2 columns / 2 rows on mobile - the images will be a lot smaller, but it will be easier to digest by the user?

**Comment by thetwopct** [comment]
I've added a new column style that display 2 columns 50/50 on mobile and up, looks lots better!

![20200827222820-Phippy and friends | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/91496799-b06e5700-e8b4-11ea-98ab-9090c8be2e17.jpg)

**Comment by cjyabraham** [comment]
Does the content need editing on dev to set this style?  I'm still seeing the single column listing of friends.

**Comment by thetwopct** [comment]
Yes it does, forgot to do it after pushing. I've done it now, but in future feel free to update the page as thats probably quicker than re-opening this issue 🤣
