### ISSUE TITLE
horizontal scroll bug

### ISSUE THREAD

**Issue by Arhell** [cncf/cncf.io#529]
![Screenshot_2](https://user-images.githubusercontent.com/26163841/165732885-77c626c8-c8d7-44d1-985a-ae08d7c7ec9e.png)
chrome last version

**Comment by cjyabraham** [comment]
Thanks for the report. Can you [go here](https://debug.thetwopercent.co.uk/) and send us the details you get?

**Comment by Arhell** [comment]
> Thanks for the report. Can you [go here](https://debug.thetwopercent.co.uk/) and send us the details you get?

Screen Width: 1536
Screen Height: 864
Viewport Width: 1519
Viewport Height: 714
Browser: Chrome
Operating System: windows
Raw Browser Info: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36

**Comment by cjyabraham** [comment]
hi @Arhell , is this issue fixed for you? I didn't think we had fixed it yet but perhaps it got fixed in some of our other changes...

**Comment by thetwopct** [comment]
There is a "fix" implemented [here](https://github.com/cncf/cncf.io/blob/eaaf20d93982173ade36a095b27b541842678d85/web/wp-content/themes/cncf-twenty-two/source/scss/core/_global.scss#L24) but the prevailing issue of Gutenberg using 100vw width on full width blocks and pushing out the scrollbar still exists and something I need to look in to further.
